"""Orchestrator script: generate all dist/ artifacts (Phase 1 + Phase 02.2).

Run with: python generate_dist.py
Prerequisites: venv activated (Python 3.11+ with all dependencies from pyproject.toml).
"""

import json
import os
import sys
from pathlib import Path

# Ensure we can import the src/ modules
sys.path.insert(0, str(Path(__file__).parent / "src"))

# Phase 1 modules
from yaml2json.convert import convert_yaml_to_json
from validation.canonical_profiles import CANONICAL_PROFILES
from validation.export_fixtures import export_test_fixtures
from validation.reference_sim import validate_all_profiles


def main():
    # Script is in packages/data-pipeline/ — go up 2 levels to repo root
    repo_root = Path(__file__).parent.parent.parent
    dist_dir = Path(__file__).parent / "dist"
    dist_dir.mkdir(parents=True, exist_ok=True)

    print("=" * 60)
    print("Phase 1 + Phase 02.2 Artifact Generation")
    print("=" * 60)

    # ── Step 1: YAML → JSON conversion ──────────────────────────
    print("\n[1/7] Converting YAML parameters to JSON...")
    yaml_dir = str(repo_root / "packages" / "tax-rules" / "parameters")
    output_parameters_dir = str(dist_dir / "parameters-v2025.1")

    result = convert_yaml_to_json(
        yaml_dir=yaml_dir,
        output_dir=output_parameters_dir,
        schema_path=None,
    )
    print(f"  ✓ Converted: {result['converted']} files")
    if result["failed"]:
        print(f"  ✗ Failed: {result['failed']} files")

    # ── Step 2: Reference simulation ───────────────────────────
    print("\n[2/7] Running openfisca-france reference simulation...")
    ref_results = validate_all_profiles(
        profiles=CANONICAL_PROFILES,
        reference_year=2025,
    )
    print(f"  ✓ Profiles: {ref_results['passed']} passed, {ref_results['failed']} failed")

    # ── Step 3: Bilingual test fixtures ────────────────────────
    print("\n[3/7] Exporting bilingual test fixtures...")
    fixture_path = export_test_fixtures(
        profiles=CANONICAL_PROFILES,
        reference_results=ref_results,
        output_dir=str(dist_dir),
    )
    print(f"  ✓ Written: {fixture_path}")

    # ── Step 4: Aggregate parameters ───────────────────────────
    print("\n[4/7] Aggregating parameters into parameters-v2025.1.json...")
    params_dir = Path(output_parameters_dir)
    aggregate = {}
    if params_dir.exists():
        for json_file in sorted(params_dir.rglob("*.json")):
            rel_path = str(json_file.relative_to(params_dir))
            with open(json_file) as f:
                aggregate[rel_path] = json.load(f)

    aggregate_path = dist_dir / "parameters-v2025.1.json"
    with open(aggregate_path, "w", encoding="utf-8") as f:
        json.dump(aggregate, f, indent=2, ensure_ascii=False)
    print(f"  ✓ Written: {aggregate_path} ({len(aggregate)} files)")

    # ── Step 5: Calibrated shock matrix (Phase 02.2 — Plan 03) ─
    print("\n[5/7] Calibrating and exporting shock matrix...")
    try:
        from shock_matrix.calibrate import calibrate_and_export

        matrix_path = calibrate_and_export(output_dir=str(dist_dir), seed=42)
        size = os.path.getsize(matrix_path)
        print(f"  ✓ Written: {matrix_path} ({size:,} bytes)")
        print(f"  Dimensions: 12×12×5×4 (2880 float32 values)")
    except ImportError as e:
        print(f"  ⚠ calibrate.py unavailable: {e}")
        print("  Skipping shock matrix calibration.")

    # ── Step 6: Synthetic population (Phase 02.2 — Plans 02,04,06) ─
    print("\n[6/7] Generating synthetic population with DP proof...")
    try:
        from synthetic_pop import generate_from_insee, export_with_dp

        print("  Training CopulaGAN (epochs=100, this may take several minutes)...")
        pipeline_result = generate_from_insee(epochs=100, num_rows=50000, seed=42)
        quality = pipeline_result["quality_report"]["fidelity"]["overall_score"]
        print(f"  ✓ Training complete — quality score: {quality:.3f}")

        print("  Injecting DP noise and exporting...")
        pop_path = export_with_dp(pipeline_result, output_dir=str(dist_dir))
        print(f"  ✓ Written: {pop_path}")
    except ImportError as e:
        print(f"  ⚠ synthetic_pop modules unavailable: {e}")
        print("  Skipping synthetic population generation.")

    # ── Step 7: dist/README.md ───────────────────────────────────
    print("\n[7/7] Writing dist/README.md...")
    readme_path = dist_dir / "README.md"
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write("""# Budget Citoyen — Distribution Artifacts

Generated by `packages/data-pipeline/generate_dist.py`.
All files are versioned with reference year 2025.

## Files

| File | Source | Description |
|------|--------|-------------|
| `parameters-v2025.1.json` | Phase 1 | Aggregated tax parameters from OpenFisca YAML files |
| `parameters-v2025.1/` | Phase 1 | Individual per-file JSON outputs |
| `bilingual_test_fixtures.json` | Phase 1 | 16 canonical profiles with openfisca reference results |
| `shockmatrix-v2025.1.parquet` | Phase 02.2 Plan 03 | Calibrated 12x12x5x4 shock matrix (hybrid IRF + elasticity) |
| `shockmatrix-v2025.1.parquet.meta.json` | Phase 02.2 Plan 03 | Sidecar with calibration methodology, breakpoints, hull |
| `population-v2025.1.json` | Phase 02.2 Plans 02-06 | 50K synthetic profiles from CopulaGAN + INSEE aggregates |
| `population-v2025.1.meta.json` | Phase 02.2 Plan 06 | DP guarantee (epsilon <= 1.0), SHA-256 hash, privacy statement |

## Regeneration

```bash
cd packages/data-pipeline
source .venv/bin/activate
python generate_dist.py
```

## Architecture

The pipeline executes in this order:
1. **Tax rules** → YAML to JSON conversion (Phase 1)
2. **Test fixtures** → OpenFisca reference simulations (Phase 1)
3. **Shock matrix** → Hybrid IRF + elasticity calibration (Phase 02.2 Plan 03)
4. **Synthetic population** → INSEE aggregate loading → CopulaGAN training → DP injection → JSON export (Phase 02.2 Plans 02, 04, 06)

All outputs are static files consumable by the webapp without server-side computation.
""")
    print(f"  ✓ README written: {readme_path}")

    print("\n" + "=" * 60)
    print("Artifact generation complete!")
    print(f"Output directory: {dist_dir}")
    print("=" * 60)


if __name__ == "__main__":
    main()
