/* webapp/sw.js
 *
 * Workbox Service Worker for Budget Citoyen (D-31).
 * Decision: CacheFirst for data, NetworkFirst for app shell, StaleWhileRevalidate for pages.
 * Strategy from D-31: warm load <1s via SW cache, cold load <3s.
 */

importScripts('https://storage.googleapis.com/workbox-cdn/releases/7.4.1/workbox-sw.js');

if (workbox) {
  workbox.core.skipWaiting();
  workbox.core.clientsClaim();

  // Precache the app shell (manifest auto-generated by workbox-build)
  workbox.precaching.precacheAndRoute(self.__WB_MANIFEST || []);

  // CacheFirst for data assets — scenario JSON, shock matrix (7-day expiration)
  workbox.routing.registerRoute(
    /\/data\/.*/,
    new workbox.strategies.CacheFirst({
      cacheName: 'data-cache-v1',
      plugins: [
        new workbox.expiration.ExpirationPlugin({
          maxAgeSeconds: 7 * 24 * 60 * 60,
        }),
      ],
    }),
  );

  // NetworkFirst for app shell (HTML/JS/CSS/SVG) — 3s timeout fallback to cache
  workbox.routing.registerRoute(
    /\.(?:html|js|css|svg)$/,
    new workbox.strategies.NetworkFirst({
      cacheName: 'app-shell-v1',
      networkTimeoutSeconds: 3,
    }),
  );

  // StaleWhileRevalidate for methodology page
  workbox.routing.registerRoute(
    /\/methodologie/,
    new workbox.strategies.StaleWhileRevalidate({
      cacheName: 'pages-cache-v1',
    }),
  );
}
